if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "Native release artifact is missing: ${INPUT}")
endif()

file(SHA256 "${INPUT}" SHA256)
file(SIZE "${INPUT}" SIZE)
set(SIGNATURE_LINE "")
if(SIGNATURE_FILE)
  if(NOT EXISTS "${SIGNATURE_FILE}")
    message(FATAL_ERROR "Update signature is missing: ${SIGNATURE_FILE}")
  endif()
  file(READ "${SIGNATURE_FILE}" SIGNATURE HEX)
  string(TOLOWER "${SIGNATURE}" SIGNATURE)
  set(SIGNATURE_LINE "      \"signature\": \"${SIGNATURE}\",\n")
endif()
file(WRITE "${OUTPUT}" "{\n")
file(APPEND "${OUTPUT}" "  \"version\": \"${VERSION}\",\n")
file(APPEND "${OUTPUT}" "  \"notes\": \"\",\n")
file(APPEND "${OUTPUT}" "  \"platforms\": {\n")
file(APPEND "${OUTPUT}" "    \"${PLATFORM}\": {\n")
file(APPEND "${OUTPUT}" "      \"url\": \"${URL}\",\n")
file(APPEND "${OUTPUT}" "      \"sha256\": \"${SHA256}\",\n")
file(APPEND "${OUTPUT}" "${SIGNATURE_LINE}")
file(APPEND "${OUTPUT}" "      \"size\": ${SIZE}\n")
file(APPEND "${OUTPUT}" "    }\n")
file(APPEND "${OUTPUT}" "  }\n")
file(APPEND "${OUTPUT}" "}\n")
